--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Vecnavium/VecnaLeaderboards
build-by-default: true
branches:
- PM4
projects:
  VecnaLeaderboards:
    path: ""
    libs:
      - src: brokiem-pm-pl/EasyUI/libEasyUI
        version: 2.0.0
...
