--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Vecnavium/VecnaLeaderboard
build-by-default: true
branches:
- main
projects:
  VecnaLeaderboards:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
      - src: Ifera/ConfigUpdater/ConfigUpdater
        version: ^1.1.0
...
