name: VecnaLeaderboards
author: Vecnavium
main: Vecnavium\VecnaLeaderboards\Main
version: "2.1.0"
api: [4.0.0]
load: STARTUP
description: A Pocketmine-MP Plugin that keeps track of Player Statistics
mcpe-protocol: [465]

permissions:
  vecnaleaderboards.manage:
    default: op
    description: "Create or delete leaderboards"
