name: VecnaLeaderboards
author: Vecnavium
main: Vecnavium\VecnaLeaderboards\Main
version: "2.1.3"
api: [4.0.0]
mcpe-protocol: [465, 471, 475]
load: STARTUP
description: A Pocketmine-MP Plugin that keeps track of Player Statistics

permissions:
  vecnaleaderboards.manage:
    default: op
    description: "Create or delete leaderboards"
