name: VecnaLeaderboards
authors:
  - Vecnavium
  - cosmicnebula200
main: Vecnavium\VecnaLeaderboards\Main
version: "2.1.5"
api: [4.0.0]
mcpe-protocol: [486]
load: STARTUP
description: A Pocketmine-MP Plugin that keeps track of Player Statistics

permissions:
  vecnaleaderboards.manage:
    default: op
    description: "Create or delete leaderboards"