#==========================================#
#Config File for VecnaLeaderboards
#==========================================#
CONFIG_VERSION: 4

# Supported languages:
# en (English)
# fr (French)

language: "en"
#====================================================================================#


#How often do you want all leaderboards to update to latest stats? (in seconds)
leaderboard-timer: 10


#Config the title to the text you want for it to display at the top for each statistic leaderboard.
#Use "&" for colors

kills: "&l&l| Kills Leaderboard |"

deaths: "&l&l| Top deaths leaderboard |"

levels: "&l&l| Levels leaderboard |"

  
#Top rankings, put 10 and only top 10 players on the leaderboard will be shown. 20 will result to top 20 and so on.
leaderboard-top-length: 10

#========================================================================#
# Levels System based on Kills from each player and rewards configuration
#========================================================================#

# Be sure you follow the configuration pattern or else you will likely face errors.
# You do not HAVE to add rewards per level but it is required to not skip levels (numbers) or else you might run through errors.

#Format for each levels
# Level Number:
#   kills: Amount of kills required to reach to the level


levels-system:
  1:
    kills: 2

  2:
    kills: 4

#====================================================================================#
